spring:
  application:
    name: "spring-boot-kafkastreams"

  cloud:
    stream:
      function:
        bindings:
          process-in-0: test-kstream-spring-cloudstream-input-topic
          process-out-0: test-kstream-spring-cloudstream-output-topic

      kafka:
        streams.binder:
          applicationId: spring-boot-springcloud-kafkastreams
          configuration:
            commit.interval.ms: 100
            cache.max.bytes.buffering: 0
            default.key.serde: org.apache.kafka.common.serialization.Serdes$VoidSerde
            default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde

  kafka:
    bootstrap-servers: dataplatform:9092

logging:
  level:
    root: info
    com.trivadis.kafkws.springboot.kafkastreamsspringcloudstream: debug